version: 2.1
jobs:
  say_hello:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "hello"
  say_bye:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "bye"

workflows:
  hello_and_bye:
    jobs:
      - say_hello
      - say_bye
